### ISSUE TITLE
Parabéns

### ISSUE THREAD

**Issue by bielmorales** [vtex/docs#14]
Então quer dizer que vocês deixam oficialmente uma biblioteca de vcs q nao da suporte a versoes de node mais antigas, pedem pra a gnt forçar a instalação de uma versão antiga pq a versao nova ta com bug(em vez de arranjar uma solução) e ainda coloca um tutorial errado pra instalar "ISSO". O lado bom é que eu nem me decepciono mais com vcs, eu dou risada junto com meus amigos desenvolvedores sobre o exemplo de NAO se seguir programando! Detalhe: vcs podiam ter tirado todo o conteudo da pasta do git e manter no readme o link https://vtex.github.io/docs/ que é exatamente a mesma coisa!

**Comment by garrucho** [comment]
Oi, @bielmorales!

O uso do gitbook em versão antiga está restrita ao fornecimento deste repositório (vtex/docs) e não impacta em absolutamente nenhum outro tipo de finalidade. Não trata-se de uma biblioteca e nem existe a intenção de que terceiros façam a _build_ deste repositório.

Este repositório é uma documentação obsoleta e não faz sentido o esforço de atualização do gitbook aqui implementado.

Seu conteúdo está sendo transferido para o nosso Help Center (help.vtex.com).
