### ISSUE TITLE
Traduzir para o espanhol

### ISSUE THREAD

**Issue by brenoc** [vtex/docs#2]

**Comment by zeluizr** [comment]
Se precisar de ajudar para o espanhol é só avisar!

**Comment by brenoc** [comment]
@zeluizr :+1: será muito bem vinda!

Vou criar a estrutura básica de tradução e dai te aviso pra você poder contribuir :)

**Comment by zeluizr** [comment]
@brenoc tranquilo, quando gerar a estrutura me avisa, que já começo a traduzir. 👊

**Comment by brenoc** [comment]
@zeluizr pronto!

Pra começar a escrever o docs, basta instalar as dependências node: `npm i` e depois rodar `gitbook serve`. Vão aparecer vários warnings, mas pode ignorá-los. Depois abrir a URL: http://localhost:4000/

O docs do Gitbook, pacote node que gera a documentação, ta aqui: http://help.gitbook.com/index.html

Todos os arquivos dentro da pasta "es/" estão ao seu dispor

**Comment by zeluizr** [comment]
@brenoc Valeu cara, agora é comigo. Vou fazer com maior velocidade possivel! 😬

**Comment by brenoc** [comment]
Deprecated
