### ISSUE TITLE
Link quebrado

### ISSUE THREAD

**Issue by garrucho** [vtex/docs#4]
Coisa simples...

Em [Models](http://vtex.github.io/docs/pt-br/portal/recursos/models.html#models), trecho "*Leia mais sobre a tag Liquid `model`.*", link:

- de `http://vtex.github.io/docs/pt-br/portal/recursos/referencias/liquid/portal/tags.html#model`
- para `http://vtex.github.io/docs/pt-br/portal/referencias/liquid/portal/tags.html#model`.

;)

**Comment by garrucho** [comment]
Mais um:

- http://vtex.github.io/docs/pt-br/portal/apps/como-criar/index.html#vtex-toolbelt - "*Leia mais sobre como usar o VTEX Toolbelt!*"
- de `http://vtex.github.io/docs/pt-br/portal/apps/referencias/toolbelt.html`
- para `http://vtex.github.io/docs/pt-br/portal/referencias/toolbelt.html`

**Comment by brenoc** [comment]
@garrucho desculpa a demora pra responder, vi que nao tinha dado watch no repo :grimacing:
